name: Check AOE2 Player Status

on:
  workflow_dispatch:
    # This allows you to manually trigger the workflow from the GitHub Actions tab.

jobs:
  run-status-check:
    runs-on: ubuntu-latest # The type of runner machine to use

    # Grant write permissions for the GITHUB_TOKEN to commit the updated JSON file
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Action to clone your repository

    - name: Set up Python
      uses: actions/setup-python@v5 # Action to set up Python environment
      with:
        python-version: '3.10' # Specify your desired Python version, e.g., '3.9', '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests python-telegram-bot pytz # Install required Python packages

    - name: Configure Git for commits
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Run player status checker script
      env:
        # Pass your GitHub Secrets as environment variables to the script
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: python aoetelegrambot.py # Make sure this matches your script's filename

    - name: Check for changes and commit updated status file
      run: |
        git add mostrecentmatch.json
        git diff-index --quiet HEAD || git commit -m "chore: Update player statuses [skip ci]"
        # Only push if there are actual changes
        git push origin HEAD || echo "No changes to commit."
